// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlb0x-3BV0ADWLWmPjc68zJ2Cp5BCwgVM',
    appId: '1:372388849933:web:eff41e2c17eb46822d6844',
    messagingSenderId: '372388849933',
    projectId: 'doctorappointment-f0d02',
    authDomain: 'doctorappointment-f0d02.firebaseapp.com',
    storageBucket: 'doctorappointment-f0d02.firebasestorage.app',
    measurementId: 'G-XDJETGHE2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWxdjoCvtRA-IPD9ZCMDAgbtl8p3qKLVo',
    appId: '1:372388849933:android:9d2dee28df6a7fed2d6844',
    messagingSenderId: '372388849933',
    projectId: 'doctorappointment-f0d02',
    storageBucket: 'doctorappointment-f0d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKkxActlqa3Dh99TZGtQLudAg-ZTm4UI',
    appId: '1:372388849933:ios:90f4be00111f2a632d6844',
    messagingSenderId: '372388849933',
    projectId: 'doctorappointment-f0d02',
    storageBucket: 'doctorappointment-f0d02.firebasestorage.app',
    iosBundleId: 'com.example.userAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkKkxActlqa3Dh99TZGtQLudAg-ZTm4UI',
    appId: '1:372388849933:ios:90f4be00111f2a632d6844',
    messagingSenderId: '372388849933',
    projectId: 'doctorappointment-f0d02',
    storageBucket: 'doctorappointment-f0d02.firebasestorage.app',
    iosBundleId: 'com.example.userAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlb0x-3BV0ADWLWmPjc68zJ2Cp5BCwgVM',
    appId: '1:372388849933:web:f735a6eaac7a6c902d6844',
    messagingSenderId: '372388849933',
    projectId: 'doctorappointment-f0d02',
    authDomain: 'doctorappointment-f0d02.firebaseapp.com',
    storageBucket: 'doctorappointment-f0d02.firebasestorage.app',
    measurementId: 'G-DZEHQRPXYX',
  );
}
